sudo: false
language: node_js
node_js:
  - "4.2" 
deploy:
  - provider: npm
    email: "reto.gmuer@zazuko.com"
    api_key:
      secure: "MnuyoHI3SGnH1wLw/3buMxhdv4/dTnwQeNVIgMVSzT5j7nJfao1ZiZ8nWG8MQdNaKggUQx06X+ENbnxdgpB9X2lMbm7z/SVyf1LZoW3vef+dezyyAr1Uy32iImeME3QtpWeH5sAKbFCveMAjAsm4i5xlYT1nf7wYKo4TMME+BxNH6Fe79Biq/1fMgW+L4ThEJ6/No+zq7EQmd6ZkfMBJJInWG1bVxZtEgsqXqHCuQKT3QOAQgiap5d2pMFHkhpjSLYrCWG5WwQhpBi35K05PMkts6FqBKIi6k8JrTE5Xi8KDvPtNwkhxCr3CWVsEfpNihaiiOeZxpwGIDmt8BqW83gz5HsxRF6kmxyaDqAuSPiUjuL8hoKgAsKlG924Dd432U8cCx9s1lEj1KoTwQdDHV0z1LhV/ietZfwFdXm5Mtw5JlcBfl02tB95TlQLMPHXY2t3ClBc+18eer8zjd5FFiOwArRg7U3f7DQoGbZk9POOGOOnOIp9qil1Az56fNB8YKUKwZlbd3jDAZ3EVd+J1MpU610TkMQ8GeFEsU2me57uprCTMsR+G9bQJTqywN/5w0rGLaTD6D7EKsvvYv5ILGWGOr+/3N5f6k3pTujykw9iJbyTwB/94m4vwhwq8e7gd6nLNj0ZOylAWzc/jJpYbAZDJFoP6obnRXKQdZouHXrg="
    on:
      tags: true
  - provider: releases
    api_key:
      secure: "ReTmWqaSqZ3a9++TJLQwTX6Ivr5+CzUVgJHDUEzGZZvoSgQ0sYkkKwWq2eyN47Rh1G37nNLoZoXw6imaGNuNVgIWCpg56mGQE53DTom/7GCGUCDhUOk6T3xA2MyPp3JJ6umh3vMn2n3e4qkYqhUsDtwEJlomWoukA7oSDmtA+tze47T7vAlofPbBZNTAjIxOwU15OYe+S+Xq2TSswL6l2gSZnB4Uts5FV+2AXUXno+dpA9UpT9ECj5QLa0XK/adjGguk9hQM9wOITJmfZleiRd8VtbbWPfKC5krIZ6Q3FTrjrJ8X76QrjjfuE2iTtYxR1QL0lWac805YpmqoGszNQ9rg043ps6bLtuC+HhLQZaufTRJ2OJF3zDObP7rxDCAy/HcNfaPB11rqJBmyY0k52lnASJ76Hg9EjfhuNa0w7n08ma+UBNuAT2QQ7hq1WGh11Ncih082Po2PLBj3fDGgsnV1jYqYA7isNEZiZcikeW4/kZ/ViPjErm0hDA93WF6Poa9B2Zaf0UH6RED2ptevHH591DDD++C9u/Oyg279tzQwM2XPlbK/1ggS0/c6jMGS+yZWdepWRgqgaFreztpEpGs7kmBDTb20MS/n7giCfLOSWPG7QLbkFESauKFilsokz5SxcSPMgABfZmSl/o2/xt40+6iKi3Iz76zM6Fa4UqI="
    file: dist/rdf-store-ldp.js
    on:
      tags: true
#  - provider: bintray
#    file: ".bintray-descriptor.json"
#    user: "reto"
#    key:
#      secure: "HWpUoWFTGAjQoA/Lb0gbKSQHt59+Bfxoo0P80lEHlrJEqkwQ3uxo2pP9ERcUi1Qhw2jG0Hz/DIEsvCdRqclr/ZavXPIMy1LAe/ZMv1TiAKOwrfeREQGdXq3OmyfUf5fNV+ZQJXNjyY+8m64T4M3nJ3bDk/d9ro1uf5hd0UOyXrM5jc7HzsJT52u0eSwYjWMnYXTurHS6P/uhVl4ZYiujea4/37dq266VYq0h5et0Y5wvfBJ2NNqQCkBV/et8bRamHfEehbOoFG6UnnC/83fDbBxACYzHSXdEN3S8l1KSemUDadTs6QgvKmA4sipwS7DckZQ1XVB0UlXE4+NwP7uE2RwNvxlfP/HeVH3LdQcpAVojYXw0/Ffg6lvWOE+G0y0/peg/BEoNhtce4IhT11ZfenYETtnX0JKIkskB104KzLuBwtiivZsspbGWoDnCaNmJ69SzC9uy7420FuYvlexp1zNU0WGf2MVguJa/ZWss25nsJiEQzvPN6pkztvgZcw2P5K9lsRbokc02QHK7gAmBn+gYfvshdqOzADAvWJnXH/wdzHbHizvSXsYK2qYVRFUsVkkWtXUwcv1yE1hqxEHG0VWkim4bYMBf4LfMGyIUg1GeSUAqjMdPGbttgV790ExuTV2r6YW0HEwMn3oD1nLc2Y3FQ5b7PeOFdBKgGTE7WiU="
#    on:
#      tags: true